### ISSUE TITLE
Links are not up to date 

### ISSUE THREAD

**Issue by ahdbk** [IBM-Bluemix-Docs/conversation#100]
Hello Guys , 

All links on the documentation are broken (404 pages)

**Comment by michelle-miller** [comment]
Hi @ahdbk. The md files in this repo are the source for the IBM Cloud Docs (html) pages. The hrefs are written such that they will work on the Docs site. That is why they all go to files with html extensions instead of md extensions. 
For example, notice that the links from this page all work: https://console.bluemix.net/docs/services/conversation/configure-workspace.html

**Comment by ttlew** [comment]
can we close this? @michelle-miller
