### ISSUE TITLE
Describing to integrate a bot built with Watson Assistant using Botkit

### ISSUE THREAD

**Issue by rodalton** [IBM-Bluemix-Docs/conversation#323]
This page really doesn't describe how to build a bot with Botkit. I've produced 2 videos hosted on IBM Code that could take readers through the steps (focused on Slack integration using Botkit), see here: 
https://developer.ibm.com/tv/integrate-ibm-watson-assistant-slack/
https://developer.ibm.com/tv/host-watson-botkit-middleware-ibm-cloud/

Feel free to include if appropriate. 

Ronan

**Comment by michelle-miller** [comment]
Sorry so late in responding. We did actually add a link to https://developer.ibm.com/tv/integrate-ibm-watson-assistant-slack/ from the integrations.html topic back in August. the topic is now obsolete due to the change in how integrations work with the new version of WA. But, this is a belated thanks for sharing the videos.
